name: Workflow to check status

on: 
  push:
    branches:
      - master 

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Simular un proceso extenso
        run: sleep 60
      
      - name: Registrar cancelacion
        if: cancelled()
        run: echo "El workflow ha sido cancelado..."
