name: Workflow to check status

on: 
  push:
    branches:
      - master 

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Primer paso correcto..
        run: echo "Hello world..."
      
      - name: Step despues del step correcto
        if: success()
        run: echo "Mensaje del segundo step correcto..."
