name: Workflow to check status

on: 
  push:
    branches:
      - master 

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Primer paso incorrecto..
        run: exit 1
      
      - name: Step despues del step fallido (Notificaciones..)
        if: failure()
        run: echo "Mensaje del segundo step despues de que fuerce el error..."
