name: Workflow to run scripts

on: 
  push:
    branches:
      - master 

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Dar privilegios y ejecutar los scripts
        run: |
          chmod +x scripts/info.sh
          ./scripts/info.sh